eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  #当前服务端口号
   port: 8755
spring:
   application:
      name: springcloud-wind-rabbitmq
   rabbitmq:
      # RabbitMQ主机地址
      host: 127.0.0.1
      # RabbitMQ端口号
      port: 5672
      # RabbitMQ用户名
      username: xdf
      # RabbitMQ密码
      password: xiedengfeng77
      # 虚拟主机名称
      virtual-host: /
      listener:
         acknowledge-mode: manual