spring:
   application:
      name: eureka-service
   profiles: peer1
server:
   #http://localhost:8761/
   port: 8761
   #清理无效节点的时间间隔
   eviction-interval-timer-in-ms: 5000
eureka:
   server:
      enableSelfPreservation: false       # 关闭自我保护模式（缺省为打开）
      evictionIntervalTimerInMs: 1000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
      contextPath: /
   instance:
      hostname: localhost
   client:
      registerWithEureka: false #将自己注册到Eureka Server，默认为True。由于当前应用就是Eureka Server，故而为false
      #fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为True,
      serviceUrl:
         #设置Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可用,分割
         defaultZone: http://peer2:8762/eureka/
---
spring:
   profiles: peer2
server:
   port: 8762
eureka:
   instance:
      hostname: peer2
   client:
      serviceUrl:
         #设置Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可用,分割
         defaultZone: http://peer1:8761/eureka/
      