spring:
   application:
      name: eureka-service
   cloud:
      config:
         uri: http://localhost:8088
server:
   #http://localhost:8761/
   port: 8761
   #清理无效节点的时间间隔
   eviction-interval-timer-in-ms: 5000
eureka:
   server:
      enableSelfPreservation: false       # 关闭自我保护模式（缺省为打开）
      evictionIntervalTimerInMs: 1000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
      contextPath: /
   instance:
      hostname: localhost
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/