spring:
   application:
      name: eureka-service
   cloud:
      config:
         uri: http://localhost:8088
server:
   #http://localhost:8761/
   port: 8761
   #开启Eureka的自我保护机制
   enable-self-preservation: true
   #清理无效节点的时间间隔
   eviction-interval-timer-in-ms: 5000
eureka:
   instance:
      hostname: localhost
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/