eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  #当前服务端口号
   port: 8766
spring:
   application:
    #当前应用名称
      name: order-service
feign:
   hystrix:
      enabled: true