spring:
   application:
    #当前应用名称
      name: config-service
   profiles:
      active: native #设置为本地启动的方式，而不是通过git
   cloud:
      config:
         server:
            native:
               searchLocations: classpath:/config   # 配置文件所在目录，classpath（类路径）和（系统文件路径） file两种  
            
server:
  #当前服务端口号
   port: 7777
   
eureka:
   instance:
      instance-id: ${spring.application.name}:${server.port}
      preferIpAddress: true                       # 设置微服务调用地址为IP优先（缺省为false）
      leaseRenewalIntervalInSeconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
      leaseExpirationDurationInSeconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
   client:
      serviceUrl:
         #注册中心的地址
         defaultZone: http://localhost:8761/eureka/